# Generated by Django 5.0.7 on 2026-03-17 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(default='✦', max_length=10)),
                ('trigger', models.CharField(choices=[('xp', 'XP milestone'), ('streak', 'Streak milestone'), ('sermons', 'Sermons completed')], default='xp', max_length=20)),
                ('threshold', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['trigger', 'threshold'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='email_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_freeze_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_freeze_earned_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
