# Generated by Django 5.0.7 on 2026-03-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='r2_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
