# Generated by Django 5.0.7 on 2026-03-16 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sermons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('url', 'Direct URL'), ('local', 'Local Upload')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('uploading', 'Uploading to Storage'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_file_id', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('sermon_title', models.CharField(blank=True, max_length=300)),
                ('sermon_speaker', models.CharField(blank=True, max_length=200)),
                ('sermon_series_id', models.IntegerField(blank=True, null=True)),
                ('sermon_date', models.DateField(blank=True, null=True)),
                ('sermon_tags', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('sermon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_job', to='sermons.sermon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
